work_dir = "."
actor_plugin_path = "actor_plugins"
actor_name = "matcher"
actor_config = "matcher.toml"
[targets]
  [targets.var_log]
  path = "/tmp/var"
  pattern = "^.+(?!lastlog)(?=(messages|cron|secure|dmesg|spooler|log))$"
  [[ actors ]]
  name = "matcher"
  config = "matcher.toml"
