work_dir = "."
actor_plugin_path = "actor_plugins"
actor_name = "matcher"
actor_config = "matcher2.toml"
[targets]
  [targets.var_log]
  path = "/var/tmp"
  pattern = "^.*(messages|cron|secure|dmesg|spooler|syslog|firewalld|tallylog|\\.log)$"
  [[ actors ]]
  name = "matcher"
  config = "matcher.toml"
