work_dir = "."
actor_plugin_path = "actor_plugins"
[[ targets ]]
  path = "/var/tmp"
  pattern = "^.*(messages|cron|secure|dmesg|spooler|syslog|firewalld|tallylog|\\.log)$"
  [[ targets.actors ]]
  name = "matcher"
  config = "matcher2.toml"
