work_dir = "."
actor_plugin_path = "actor_plugins"
[[ targets ]]
  path = "/var/log"
  pattern = "^.*(messages|cron|secure|dmesg|spooler|syslog|firewalld|tallylog|\\.log)$"
  [[ targets.actors ]]
  name = "sender"
  config = "sender.toml"
  [[ targets.actors ]]
  name = "matcher"
  config = "matcher1.toml"
