auto_reload = 5
notifier_plugin_path = "notifier_plugins"
skip_notify="false"

[[file_matchers]]
  pattern="^.+messages.+$"
  skip_notify="false"
  label="error log"
  [[notifires]]
    name="mail"
    config="mail.toml"
  [[msg_matchers]]
    pattern="^.+error.+$"

