auto_reload = 5

[notifiers]

  [notifiers.my_mail]
  name="mail"
  config="mail.toml"

[[file_matchers]]
    pattern="^.+message.+$"
    expire=172800
    notifire="my_mail"
    mode="normal"
    [[msg_matchers]]
        pattern="^.+ error.+$"

