auto_reload = 1

[notifiers]

  [notifiers.my_mail]
  name="mail"
  config="mail.toml"

[matchers]

  [matchers.error_message]
  path_pattern="^.+message.+$"
  msg_pattern="^.+ error.+$"
  expire=172800
  notifire="my_mail"
  mode="normal"
