auto_reload = 5
notifier_plugin_path = "notifier_plugins"
skip_notify=false

[[ path_matchers ]]
  pattern="^.+(messages|syslog).+$"
  skip_notify=false
  label="matcher 2"
  [[ path_matchers.notifires ]]
    name="mailsender"
    config="mailsender.toml"
  [[ path_matchers.msg_matchers ]]
    pattern="^.+[eE][rR][rR].+$"
  [[ path_matchers.msg_matchers ]]
    pattern="^.+[wW][aA][rR][nN].+$"
