auto_reload = 5
notifier_plugin_path = "notifier_plugins"
skip_notify="false"

[[file_matchers]]
  pattern="^.+messages.+$"
  skip_notify="false"
  label="matcher 2"
  [[notifires]]
    name="mailsender"
    config="mailsender.toml"
  [[msg_matchers]]
    pattern="^.+[eE][rR][rR].+$"
  [[msg_matchers]]
    pattern="^.+[wW][aA][rR][nN].+$"

