save_path = "save"
auto_reload = 1

[notifier]

  [notifier.my_mail]
  plugin="mail"
  config="mail.toml"

[matcher]

  [matcher.error_message]
  file_pattern="^.+message.+$"
  msg_pattern="^.+ error.+$"
  expire=172800
  notifire="my_mail"
  mode="normal"
